title: Jayasekara Kapukotuwa
logo: /assets/img/Navoda.jpg
# description: Technological University of the Shannon
email: j.kapukotuwa@research.ait.ie
# show_downloads: true
theme: jekyll-theme-minimal
